name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: git config user.email "JJamesWWang@gmail.com"
      - run: git config user.name "JJamesWWang"
      - run: npm run deploy
